print("Happy birthday to you!!")
print("Happy birthday to you!!")
print("Happy birthday dear ___")
print("Happy birthday to you!!")
x = input("Whose birthday was it again?")
print("Happy birthday to you!!")
print("Happy birthday to you!!")
print("Happy birthday dear " + x)
print("Happy birthday to you!!")